Vagrant.configure("2") do |config|
  config.vm.provider :cloudstack do |cloudstack|

    cloudstack.host    = "compute.jp-east.idcfcloud.com"
    cloudstack.path    = "/client/api"
    cloudstack.port    = "443"
    cloudstack.scheme  = "https"

    cloudstack.api_key    = "#{ENV['CLOUDSTACK_API_KEY']}"
    cloudstack.secret_key = "#{ENV['CLOUDSTACK_SECRET_KEY']}"

    # 仮想マシン作成のパラメータ
    cloudstack.zone_name             = "tesla"
    cloudstack.template_name         = "Ubuntu Server 14.04 LTS 64-bit"
    cloudstack.service_offering_name = "light.S1"
    cloudstack.network_type          = "Advanced"
    cloudstack.network_name          = "network1"
  end
end
