Dotenv.load

Vagrant.configure("2") do |config|

  config.vm.box = "atsaki/idcfcloud_ubuntu_14.04"

  config.ssh.username         = "root"
  config.ssh.private_key_path = "#{ENV['VAGRANT_SSH_PRIVATE_KEY']}"

  n = 3
  (1..n).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.provider :cloudstack do |cloudstack, override|
        cloudstack.display_name = "node#{i}"
        cloudstack.pf_ip_address_id = "#{ENV['CLOUDSTACK_PF_IP_ADDRESS_ID']}"
        cloudstack.pf_public_port   = "#{2200 + i}"
        override.ssh.port           = "#{2200 + i}"
        cloudstack.pf_private_port  = "22"
        cloudstack.keypair          = "#{ENV['CLOUDSTACK_SSH_KEYPAIR']}"
      end

      node.vm.provision "docker" do |d|
        d.pull_images "swarm"
      end

      node.vm.provision "shell" do |s|
        s.inline = <<-EOS
          echo 'DOCKER_OPTS="-H tcp://0.0.0.0:2375 ${DOCKER_OPTS}"' >> /etc/default/docker
          service docker restart

          echo 'export DOCKER_HOST=tcp://localhost:2375' >> ~/.bashrc
        EOS
      end
    end
  end
end
