Dotenv.load

Vagrant.configure("2") do |config|

  config.vm.box = "idcfcloud_ubuntu_14.04"

  config.ssh.username         = "root"
  config.ssh.private_key_path = "#{ENV['VAGRANT_SSH_PRIVATE_KEY']}"

  (1..3).each do |i|
    config.vm.define "node0#{i}" do |minion|
      minion.vm.provider :cloudstack do |cloudstack, override|
        cloudstack.display_name = "node0#{i}"
        cloudstack.pf_ip_address_id = "#{ENV['CLOUDSTACK_PF_IP_ADDRESS_ID']}"
        cloudstack.pf_public_port   = "220#{i}"
        override.ssh.port           = "220#{i}"
        cloudstack.pf_private_port  = "22"
        cloudstack.keypair          = "#{ENV['CLOUDSTACK_SSH_KEYPAIR']}"
      end

      minion.vm.provision :shell do |s|
        s.inline = <<-'EOS'
          apt-get -y update
          apt-get install -y git golang aufs-tools cgroup-bin

          grep -q GOPATH ~/.bashrc
          if [ $? -ne 0 ]
          then
            echo "export GOPATH=/root" >> ~/.bashrc
            echo "export PATH=$PATH:/root/bin" >> ~/.bashrc
          fi
          export GOPATH=/root

          go get github.com/docker/swarm
          go install github.com/docker/swarm

          [ -f /usr/local/bin/docker ] || curl -s -o /usr/local/bin/docker https://master.dockerproject.com/linux/amd64/docker
          chmod +x /usr/local/bin/docker

          nohup docker -d -H 0.0.0.0:2375 0<&- &>/dev/null &
        EOS
      end
    end
  end
end
